node {
    def revision = env.BUILD_NUMBER
    def image = "docker.nexus.archi-lab.io/archilab/prox-web-client"
    def version = ""
    def packageJSON = ""

    stage('Build') {

      //script {
      //  packageJSON = readJSON file: 'package.json'
      //  version = packageJSON.version
      //}

        //git url: 'https://github.com/Archi-Lab/prox-web-client.git'
        //git branch: 'jenkins-migration'

        def packageJSON = readJSON file: 'package.json'
        version = packageJSON.version

        echo "\"${version}\""

        echo "\"${image}:${version}-${revision}\""

        sh "docker build -t ${image}:${revision} -f ./src/docker/Dockerfile ."

        docker.withRegistry('https://docker.nexus.archi-lab.io', 'archilab-nexus-jenkins') {
          sh "docker push ${image}:${revision}"
        }
    }

    stage('Deploy') {
        docker.withServer('tcp://10.10.10.41:2376', 'prox-prod-certs') {
            def pom = readJSON file: 'package.json'
            def image2 = pom.version

            echo "\"${image2}\""

            //docker.withRegistry('https://docker.nexus.archi-lab.io', 'archilab-nexus-jenkins') {
            //    sh "env IMAGE=${image} TAG=${tag} docker stack deploy --with-registry-auth -c src/docker/docker-compose.yml -c src/docker/docker-compose.prod.yml ${image}"
            //}
        }
    }
}
